replicaCount: 2
image:
  repository: cuegrowth-api
  tag: "v1"
  pullPolicy: IfNotPresent # Important for local images!

env:
  natsUrl: "nats://nats.app-workload.svc:4222"
  valkeyHost: "valkey-redis-master.app-workload.svc"

resources: # [cite: 33]
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi